#IMPORTAMOS LA FUNCION DEL ARCHIVO QUE CONTIENE LA FUNCION
from ejercicio6 import funcion6;
#AÑADIMOS UN PAR DE INPUTS POR TECLADO  Y LOS PASAMOS A ENTEROS
a = int(input("sumando 1: "))
b = int(input("sumando 2: "))
#LLAMAMOS A LA FUNCION USANDO LOS INPUTS COMO PARAMETROS
funcion6(a,b);
